name: basf_weather_app_for_malaysia_scuba_diving
description: "Weather App for Scuba Diving Spots in Malaysia BASF Digital Hub KL - Technical Assessment"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  location: ^7.0.1
  http: ^1.2.2
  provider: ^6.1.2
  uuid: ^4.5.1
  shared_preferences: ^2.3.5
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.16
  gauge_indicator: ^0.4.3
  intl: ^0.20.1
  cached_network_image: ^3.4.1
  path_provider: ^2.1.5
  flutter_native_splash: ^2.4.4
  flutter_launcher_icons: ^0.14.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  fonts:
    - family: PBS
      fonts:
        - asset: assets/fonts/PublicSans-VariableFont_wght.ttf
    - family: PBSEB
      fonts:
        - asset: assets/fonts/PublicSans-ExtraBold.ttf
    - family: PBSLT
      fonts:
        - asset: assets/fonts/PublicSans-Light.ttf
    - family: PBSRG
      fonts:
        - asset: assets/fonts/PublicSans-Regular.ttf
    - family: PBSMD
      fonts:
        - asset: assets/fonts/PublicSans-Medium.ttf
    - family: PBSTH
      fonts:
        - asset: assets/fonts/PublicSans-Thin.ttf

  assets:
    - assets/svg/sw_calendar.svg
    - assets/svg/sw_eye.svg
    - assets/svg/sw_map.svg
    - assets/svg/sw_options.svg
    - assets/svg/sw_pressure.svg
    - assets/svg/sw_sunset.svg
    - assets/svg/sw_thermometer.svg
    - assets/svg/sw_tides.svg
    - assets/svg/sw_tides_night.svg
    - assets/svg/sw_water.svg
    - assets/svg/sw_waves.svg
    - assets/svg/sw_wind.svg
    - assets/svg/sw_search.svg
    - assets/svg/sw_options_circle.svg
    - assets/svg/sw_average.svg
    - assets/svg/sw_logo.svg
    - assets/svg/sw_logo_2.svg
    - assets/svg/sw_tides_day.svg
    - assets/svg/sw_tides_low.svg
    - assets/svg/sw_sun.svg
    - assets/svg/app_icon.PNG
    - assets/images/sw_icon.png
    - assets/images/sw_icon_1152.png
    - assets/images/sw_icon_960.png
    - assets/images/sw_icon_288_no_bg.png
    - assets/images/sw_icon_250_no_bg.png


flutter_native_splash:
  color: "#338db8"
  image: assets/svg/app_icon.PNG
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: center
  fullscreen: true

  android_12:
    image: assets/images/sw_icon_960.png
    icon_background_color: "#338db8"



flutter_launcher_icons:
  image_path: "assets/images/sw_icon.png"

  android: "launcher_icon"
  min_sdk_android: 24
  adaptive_icon_background: "#338db8"
  adaptive_icon_foreground: "assets/images/sw_icon.png"
  adaptive_icon_monochrome: "assets/images/sw_icon.png"

  ios: true
  image_path_ios: "assets/images/sw_icon.png"
  remove_alpha_channel_ios: true
